#spring:
#  config:
#    activate:
#      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Account related QA APIs of Accounts Microservice"
  contactDetails:
    name: "Gaurav Kumar - QA Team"
    email: "2S7Hs@example.com"
    phone: "1234567890"
  onCallSupport:
    -(091) 334-1234
    -(091) 334-5678

