#spring:
#    config:
#        activate:
#            on-profile: "prod"
build:
    version: "1.0"

loans:
    message: "Welcome to Cards related Prod APIs of Cards Microservice"
    contactDetails:
        name: "Gaurav Kumar - Cards Production Team"
        email: "production@example.com"
        phone: "1234567890"
    onCallSupport:
        - (091) 434-1234
        - (091) 434-5678
