#spring:
#    config:
#        activate:
#            on-profile: "qa"
build:
  version: "2.0"

loans:
  message: "Welcome to Loans related QA APIs of Loans Microservice"
  contactDetails:
    name: "Gaurav Kumar - Loan QA Team"
    email: "qa@example.com"
    phone: "1234567890"
  onCallSupport:
    -(091) 334-1234
    -(091) 334-5678
